### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by rosendi** [essserrr/Sendsay-console#2]
Здравствуйте, завтра 29 июля будет произведено ревью. После мы свяжемся с вами.

В задании было сказано, что нужно открыть ПР, чтобы мы могли оставить комментарии (если нам понравится в целом подход к коду и тд).

Просьба открыть ПР например из master в любой чистый бренч.

**Comment by trikashny** [comment]
Выберите удобный для вас день и время https://calendly.com/sendsay_hr/meeting

**Comment by essserrr** [comment]
> @essserrr добрый день. Ревью произведен. Мой коллега чуть позже отправить ссылку для записи.
> 
> P.S. Если ПР за день до интервью не будет открыт, интервью не состоится.

Вас, наверное, смутило наличие двух репозиториев. Я приглашал ревьюверов в приватную версию репо.  Там открыт ПР. Ну да не важно, теперь он открыт еще и тут.

**Comment by rosendi** [comment]
ОК 👍
